---
# Burp Suite settings
burpsuite_cacert_path: "{{ burpsuite_extras_dir }}/PortSwigger_CA.der"
burpsuite_extras_dir: "{{ kali_user_details.home }}/BurpSuiteExtras"
burpsuite_user: "{{ kali_user }}"

# Git repositories to clone to /opt
# Various projects that are either not in Kali or are updated more freqently than Kali repos
git_repos:
  - name: BloodHound
    repo: https://github.com/BloodHoundAD/BloodHound.git
  - name: github-search
    repo: https://github.com/gwen001/github-search
  - name: nishang
    repo: https://github.com/samratashok/nishang.git
  - name: odat
    repo: https://github.com/quentinhardy/odat.git
  - name: phpggc
    repo: https://github.com/ambionics/phpggc.git
  - name: PowerSploit
    repo: https://github.com/PowerShellMafia/PowerSploit.git
  - name: privilege-escalation-awesome-scripts-suite
    repo: https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite.git
  - name: peda
    repo: https://github.com/longld/peda.git
  - name: wesng
    repo: https://github.com/bitsadmin/wesng.git

# Add any private repos you want here
#private_repos:
  #- name: 
  #  repo: 
  #  version: 

# apt packages to install
kali_packages:
  - awscli
  - bloodhound
  - cmake
  - default-jdk
  - dkms
  - docker.io
  - docker-compose
  - gdb
  - ghidra
  - gobuster
  - golang-go
  - htop
  - irssi
  - libimage-exiftool-perl
  - libldns-dev
  - libreoffice
  - libssl-dev
  - linux-headers-generic
  - ltrace
  - lz4
  - massdns
  - maven
  - mingw-w64
  - oscanner
  - payloadsallthethings
  - pypy3
  - python3-venv
  - redis-tools
  - seclists
  - smtp-user-enum
  - sipvicious
  - tnscmd10g
  - tree
  - wireguard
  - wkhtmltopdf
  - xclip
  - xrdp

# Set as the user account that runs the ansible playbook
kali_user: "{{ lookup('env','USER') }}"

# Add any files raw files you want downloaded here
misc_downloads:
  - url: https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy64
    dest: /opt/pspy/pspy64
    mode: '755'
  - url: https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy64s
    dest: /opt/pspy/pspy64s
    mode: '755'
# Needed to install python2 pip packages on Kali, old PoCs can be broken without this
  - url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: /opt/pip2/get-pip.py
    mode: '750'
# Files below are fonts needed for teh p10k ohmyzsh theme
  - url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf
    dest: /usr/share/fonts/truetype/hacknf/Hack-Regular-NF.ttf
    mode: '644'
  - url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete%20Mono.ttf
    dest: /usr/share/fonts/truetype/hacknf/Hack-Regular-Mono-NF.ttf
    mode: '644'
  - url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete.ttf
    dest: /usr/share/fonts/truetype/hacknf/Hack-Italic-NF.ttf
    mode: '644'
  - url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete%20Mono.ttf
    dest: /usr/share/fonts/truetype/hacknf/Hack-Italic-Mono-NF.ttf
    mode: '644'
  - url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete.ttf
    dest: /usr/share/fonts/truetype/hacknf/Hack-BoldItalic-NF.ttf
    mode: '644'
  - url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete%20Mono.ttf
    dest: /usr/share/fonts/truetype/hacknf/Hack-BoldItalic-Mono-NF.ttf
    mode: '644'
  - url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete.ttf
    dest: /usr/share/fonts/truetype/hacknf/Hack-Bold-NF.ttf
    mode: '644'
  - url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete%20Mono.ttf
    dest: /usr/share/fonts/truetype/hacknf/Hack-Bold-Mono-NF.ttf
    mode: '644'

# Requires shell install to pass ZSH env var to shell script when installing ohmyzsh
shell_installs:
  - cmd: ZSH=~/.local/share/oh-my-zsh sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    dest: ~/.local/share/oh-my-zsh/oh-my-zsh.sh

# Add anything installed via cli here
cmd_installs:
  - cmd: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.local/share/oh-my-zsh/custom/themes/powerlevel10k
    dest: ~/.local/share/oh-my-zsh/custom/themes/powerlevel10k
  - cmd: python2 /opt/pip2/get-pip.py
    dest: /usr/local/bin/pip2

python_pip_packages:
  - name: setuptools
    creates: "/usr/local/lib/python2.7/dist-packages/setuptools"
  - name: cffi
    creates: "/usr/lib/python2.7/dist-packages/cffi"
  - name: dpkt
    creates: "/usr/lib/python2.7/dist-packages/cffi"
  - name: scapy
    creates: "/usr/local/lib/python2.7/dist-packages/scapy"
  
python_pip3_packages:
  - setuptools
  - patator
  - pipenv
  - pipx
  - poetry
  - roadrecon

python_pipx_packages:
  - name: git+https://github.com/Tib3rius/AutoRecon.git
    bin: "{{ kali_user_details.home }}/.local/bin/autorecon"
  - name: droopescan
    bin: "{{ kali_user_details.home }}/.local/bin/droopescan"
  - name: pwntools
    bin: "{{ kali_user_details.home }}/.local/bin/pwn"
  - name: roadrecon
    bin: "{{ kali_user_details.home }}/.local/bin/roadrecon"
  - name: xkcdpass
    bin: "{{ kali_user_details.home }}/.local/bin/xkcdpass"
  - name: xortool
    bin: "{{ kali_user_details.home }}/.local/bin/xortool"
  - name: oletools
    bin: "{{ kali_user_details.home }}/.local/bin/olevba"

ruby_gem_packages:
  - winrm
  - winrm-fs
  - stringio
  - evil-winrm

# Add any files you want copied into a new location here
config_files:
  - name: .tmux.conf
    src: files/tmux
    dest: "{{ kali_user_details.home }}"
    mode: '640'
  - name: .tmux.conf.local
    src: files/tmux
    dest: "{{ kali_user_details.home }}"
    mode: '640'
  - name: .gdbinit
    src: files/gdb
    dest: "{{ kali_user_details.home }}"
    mode: '640'
  - name: global-patterns.toml
    src: files/autorecon
    dest: "{{ kali_user_details.home }}/.config/AutoRecon"
    mode: '640'
  - name: port-scan-profiles.toml
    src: files/autorecon
    dest: "{{ kali_user_details.home }}/.config/AutoRecon"
    mode: '640'
  - name: service-scans.toml
    src: files/autorecon
    dest: "{{ kali_user_details.home }}/.config/AutoRecon"
    mode: '640'
  - name: .gitconfig
    src: files/git
    dest: "{{ kali_user_details.home }}"
    mode: '640'
  - name: .gitignore
    src: files/git
    dest: "{{ kali_user_details.home }}"
    mode: '640'
  - name: .gitconfig.local
    src: files/git
    dest: "{{ kali_user_details.home }}"
    mode: '640'
  - name: bumrush
    src: files/scripts
    dest: /usr/local/bin
    mode: '755'
  - name: extract
    src: files/scripts
    dest: /usr/local/bin
    mode: '755'
  - name: vimrc
    src: files/vim
    dest: "{{ kali_user_details.home }}/.config/vim"
    mode: '640'
  - name: wgetrc
    src: files/wget
    dest: "{{ kali_user_details.home }}/.config/wget"
    mode: '640'
  - name: .zshenv
    src: files/zsh
    dest: "{{ kali_user_details.home }}"
    mode: '640'
  - name: .zshrc
    src: files/zsh
    dest: "{{ kali_user_details.home }}/.config/zsh"
    mode: '640'
  - name: .localrc
    src: files/zsh
    dest: "{{ kali_user_details.home }}/.config/zsh"
    mode: '640'
  - name: .zsh_paths
    src: files/zsh
    dest: "{{ kali_user_details.home }}/.config/zsh"
    mode: '640'
  - name: .zsh_aliases
    src: files/zsh
    dest: "{{ kali_user_details.home }}/.config/zsh"
    mode: '640'
  - name: .zsh_autocomp
    src: files/zsh
    dest: "{{ kali_user_details.home }}/.config/zsh"
    mode: '640'
  - name: .zsh_functions
    src: files/zsh
    dest: "{{ kali_user_details.home }}/.config/zsh"
    mode: '640'
  - name: p10k.sh
    src: files/zsh
    dest: "{{ kali_user_details.home }}/.config/zsh"
    mode: '640'

delete_files:
  - "{{ kali_user_details.home }}/.zsh_history"
  - "{{ kali_user_details.home }}/.zshrc"
  - "{{ kali_user_details.home }}/.zshrc.pre-oh-my-zsh"
  - "{{ kali_user_details.home }}/.bashrc"
  - "{{ kali_user_details.home }}/.bashrc.original"
