---
# Playbook for Kali

# Configure Kali
- hosts: kali
  become: true
  tasks:
    # AppArmor
    - name: Enable AppArmor
      ansible.builtin.systemd:
        name: apparmor.service
        state: started
        enabled: true

    # Disable automatic updates
    - name: Disable apt systemd timers
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - apt-daily.timer
        - apt-daily-upgrade.timer

    - name: Prevent apt services from running
      ansible.builtin.systemd:
        name: "{{ item }}"
        masked: true
      loop:
        - apt-daily.service
        - apt-daily-upgrade.service

    - name: Disable apt periodic updates
      ansible.builtin.template:
        src: templates/apt/10periodic.j2
        dest: /etc/apt/apt.conf.d/10periodic
        owner: root
        group: root
        mode: '644'

    # Metasploit
    - name: Enable Postgresql service
      ansible.builtin.systemd:
        name: postgresql.service
        state: started
        enabled: true

    - name: Check msfdb status
      ansible.builtin.command: msfdb status
      register: msfdb_status
      changed_when: false

    - name: Initialize msfdb
      ansible.builtin.command: msfdb init
      when: "'No configuration file found' in msfdb_status.stdout"

    # OpenSSL
    - name: Configure OpenSSL
      ansible.builtin.lineinfile:
        path: /etc/ssl/openssl.cnf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - regexp: "^MinProtocol ="
          line: "MinProtocol = None"
        - regexp: "^CipherStrings ="
          line: "CipherStrings = DEFAULT"

    # Firefox ESR
    - name: Deploy Firefox ESR policy
      ansible.builtin.template:
        src: templates/firefox/policies.json.j2
        dest: /usr/share/firefox-esr/distribution/policies.json
        owner: root
        group: root
        mode: '644'

    # Resolvconf for WireGuard
    # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939904
    - name: Symlink resolvconf to resolvectl
      ansible.builtin.file:
        src: /usr/bin/resolvectl
        dest: /usr/local/bin/resolvconf
        state: link

    - name: Enable systemd-resolved.service
      ansible.builtin.systemd:
        name: systemd-resolved.service
        state: started
        enabled: true
